#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Nov 05 19:06:54 CST 2024
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim mb_preset_wrapper_behav -key {Behavioral:sim_1:Functional:mb_preset_wrapper} -tclbatch mb_preset_wrapper.tcl -protoinst "protoinst_files/mb_preset.protoinst" -log simulate.log"
xsim mb_preset_wrapper_behav -key {Behavioral:sim_1:Functional:mb_preset_wrapper} -tclbatch mb_preset_wrapper.tcl -protoinst "protoinst_files/mb_preset.protoinst" -log simulate.log

