set_property PACKAGE_PIN J2 [get_ports {not_Y[0]}]
set_property PACKAGE_PIN L1 [get_ports {not_Y[1]}]
set_property PACKAGE_PIN M2 [get_ports {not_Y[2]}]
set_property PACKAGE_PIN M1 [get_ports {not_Y[3]}]
set_property PACKAGE_PIN N2 [get_ports {not_Y[4]}]
set_property PACKAGE_PIN P1 [get_ports {not_Y[5]}]
set_property PACKAGE_PIN P2 [get_ports {not_Y[6]}]
set_property PACKAGE_PIN R1 [get_ports {not_Y[7]}]
set_property PACKAGE_PIN T3 [get_ports A]
set_property PACKAGE_PIN U3 [get_ports B]
set_property PACKAGE_PIN T4 [get_ports C]
set_property PACKAGE_PIN V3 [get_ports G1]
set_property PACKAGE_PIN V4 [get_ports not_G2]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {not_Y[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {not_Y[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {not_Y[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {not_Y[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {not_Y[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {not_Y[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {not_Y[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {not_Y[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports A]
set_property IOSTANDARD LVCMOS18 [get_ports B]
set_property IOSTANDARD LVCMOS18 [get_ports C]
set_property IOSTANDARD LVCMOS18 [get_ports G1]
set_property IOSTANDARD LVCMOS18 [get_ports not_G2]
set_property IOSTANDARD LVCMOS18 [get_ports not_G3]


set_property PACKAGE_PIN W4 [get_ports not_G3]


set_property PULLDOWN true [get_ports A]
set_property PULLDOWN true [get_ports B]
set_property PULLDOWN true [get_ports C]
set_property PULLDOWN true [get_ports G1]
set_property PULLDOWN true [get_ports not_G2]
set_property PULLDOWN true [get_ports not_G3]
